INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "random_translation", "normalize"]

DATASET:
  NAME: "SSDGTerraIncognita"
  NUM_LABELED: 300

MODEL:
  BACKBONE:
    NAME: "resnet18"
    PRETRAINED: True
